import { execSync } from "child_process"
import { Skill, SkillInput, SkillResult, ExecutionContext } from "../interface"
import { createMetadataComment } from "../../utils/metadata"

export class PrCreatorSkill implements Skill {
  name = "pr-creator"
  description = "Commit changes, push branch, and open a PR linked to the issue."

  async execute(input: SkillInput, context: ExecutionContext): Promise<SkillResult> {
    const issueContext = input.issue_context ?? context.issueContext
    const workspace = input.workspace as string
    const branch = input.branch as string
    const diffSummary = (input.diff_summary as string) || ""
    const testResults = input.test_results ?? null
    const inputWarnings = (input.warnings as string[]) || []

    if (!workspace) {
      return {
        success: false,
        data: {},
        warnings: [],
        error: "Missing required input: workspace",
      }
    }

    if (!branch) {
      return {
        success: false,
        data: {},
        warnings: [],
        error: "Missing required input: branch",
      }
    }

    const warnings: string[] = []

    try {
      // 1. Stage all changes
      try {
        execSync("git add .", { cwd: workspace, stdio: "pipe" })
      } catch (err: any) {
        return {
          success: false,
          data: {},
          warnings: [],
          error: `Failed to stage changes: ${err.message}`,
        }
      }

      // 2. Commit with descriptive message referencing issue
      const commitMessage = `fix: address issue #${issueContext.issueNumber} - ${issueContext.issueTitle}`
      try {
        execSync(`git commit -m "${commitMessage}"`, {
          cwd: workspace,
          stdio: "pipe",
        })
      } catch (err: any) {
        // Check if there's nothing to commit
        if (err.message?.includes("nothing to commit")) {
          return {
            success: false,
            data: {},
            warnings: [],
            error: "No changes to commit",
          }
        }
        return {
          success: false,
          data: {},
          warnings: [],
          error: `Failed to commit: ${err.message}`,
        }
      }

      // 3. Push branch to remote
      try {
        execSync(`git push origin ${branch}`, {
          cwd: workspace,
          stdio: "pipe",
          timeout: 60_000,
        })
      } catch (err: any) {
        return {
          success: false,
          data: {},
          warnings: [],
          error: `Failed to push branch: ${err.message}`,
        }
      }

      context.logger.info("Pushed branch to remote", { branch })

      // 4. Build PR data with signed metadata
      const prTitle = `[AgentGit] Fix #${issueContext.issueNumber}: ${issueContext.issueTitle}`

      const metadata = {
        type: "pr",
        issue_number: issueContext.issueNumber,
        repo: `${issueContext.repoOwner}/${issueContext.repoName}`,
        branch,
        created_by: "agentgit",
        timestamp: new Date().toISOString(),
      }

      const prBodyContent = buildPrBody(
        issueContext,
        diffSummary,
        testResults,
        inputWarnings,
      )

      const prBody = createMetadataComment(metadata, prBodyContent, context.signingSecret)

      return {
        success: true,
        data: {
          title: prTitle,
          body: prBody,
          head: branch,
          base: "main",
          issue_number: issueContext.issueNumber,
          owner: issueContext.repoOwner,
          repo: issueContext.repoName,
          commit_message: commitMessage,
        },
        warnings,
      }
    } catch (err: any) {
      return {
        success: false,
        data: {},
        warnings: [],
        error: `PR creation failed: ${err.message}`,
      }
    }
  }
}

/**
 * Build the human-readable portion of the PR body.
 */
function buildPrBody(
  issueContext: { issueNumber: number; issueTitle: string },
  diffSummary: string,
  testResults: any,
  warnings: string[],
): string {
  const lines: string[] = []

  lines.push(`## Summary`)
  lines.push(``)
  lines.push(`Closes #${issueContext.issueNumber}`)
  lines.push(``)
  lines.push(`This PR was automatically generated by AgentGit to address:`)
  lines.push(`**${issueContext.issueTitle}**`)
  lines.push(``)

  if (diffSummary) {
    lines.push(`## Changes`)
    lines.push(``)
    lines.push(diffSummary)
    lines.push(``)
  }

  if (testResults) {
    lines.push(`## Test Results`)
    lines.push(``)
    lines.push(`\`\`\``)
    lines.push(typeof testResults === "string" ? testResults : JSON.stringify(testResults, null, 2))
    lines.push(`\`\`\``)
    lines.push(``)
  }

  if (warnings.length > 0) {
    lines.push(`## Warnings`)
    lines.push(``)
    for (const warning of warnings) {
      lines.push(`- ${warning}`)
    }
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(`*Generated by [AgentGit](https://github.com/agentgit) bot*`)

  return lines.join("\n")
}
